sudo: required

branches:
  except:
    - weblate
services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run --rm -v $(pwd):/app opensourcepos/composer:ci4 composer install
  - version=$(grep application_version app/Config/App.php | sed "s/.*=\s'\(.*\)';/\1/g")
  - sed -i "s/commit_sha1 = 'dev'/commit_sha1 = '$rev'/g" app/Config/OSPOS.php
  - echo "$version-$branch-$rev" 
  - npm version "$version-$branch-$rev" --force || true
  - docker run --privileged --rm -it -v $(pwd):/app -w /app node
    sh -c "npm install && npm install -g gulp && npm run build"
  - docker build . --target ospos -t ospos
  - docker build app/Database/ -t "jekkos/opensourcepos:sql-$TAG"
env:
  global:
  - BRANCH=$(echo ${TRAVIS_BRANCH} | sed s/feature\\///)
  - TAG=${TRAVIS_TAG:-$BRANCH}
  - date=`date +%Y%m%d%H%M%S` && branch=${TRAVIS_BRANCH} && rev=`git rev-parse --short=6 HEAD` 
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker tag "ospos:latest"
    "jekkos/opensourcepos:$TAG" && docker push "jekkos/opensourcepos:$TAG" && docker push "jekkos/opensourcepos:sql-$TAG"
  - sudo mv dist/opensourcepos.tgz "dist/opensourcepos.$version.$rev.tgz"
  - sudo mv dist/opensourcepos.zip "dist/opensourcepos.$version.$rev.zip"
before_deploy:
  - npm set //npm.pkg.github.com/:_authToken "$NPM_TOKEN"
deploy:
  - provider: npm
    file: dist/opensourcepos.$version.$rev.tgz
    registry: npm.pkg.github.com
    email: jeroen@steganos.dev
    skip_cleanup: true
    api_key:
      secure: "bmOfMoGBi+wTEdTbIB7wPenNTCZrmHAa05xZnMxZSOjxplZpnZSO4Tvnnkihz9LpbF3xT1hm76AJJuZonu2HKtUez+6L4Fg+i/jS8Ij/BZlbvKBVTeB+2yN09ncXNmObnl1bShtm90d2WYQJKk3NJGuEboFQNxwJLYJXg33iMhc="

    on:
      all_branches: true
  - provider: releases
    file: dist/opensourcepos.$version.$rev.zip
    name: "OpensourcePos $version"
    release_notes_file: WHATS_NEW.txt
    prerelease: true
    skip_cleanup: true

    user: jekkos
    overwrite: true
    api_key:
      secure: Ax25mMRDfHVf/HjRwqxYJe2oMnWC4sc2aKIiUxAOviVJJSCl4GMWhcFlUNnFsDcKIg2ofEGMVD6b9cTBuOwPDvymUDFnLNCCgDWve+vRDdWaTkTipn77Qk4c9UO9VvuzlPSKopChefPHlQ0n1rEmAMiKIXuqjUlNGqybW4FLP4E=
    on:
      tags: true
      branch: master
